### PR TITLE
updated to use latest lvm cookbook with di-ruby-lvm-attrib version fi…

### PR DESCRIPTION
**Pull request by Stromweld**
…x for latest lvm updates

### CODE REVIEW

**Comment by Stromweld** [comment]
this also resolves issue #38

**Comment by Stromweld** [comment]
anything I can do to push to get this merged and released to the supermarket?

**Comment by rshade** [comment]
if you can pin it to `cookbook 'lvm', '~> 1.6.1'`, I can merge it, and look into uploading it

**Comment by Stromweld** [comment]
I can do that, but why does it need to be pinned? There has been at least twice now that because of pinning we have had to wait for lvm and this cookbook to be updated to fix the di-ruby-lvm-attrib issue after lvm updates. I'd think it'd be better to pin if breaking issues are found and then pin it at that time to older version.

**Comment by Stromweld** [comment]
made the change to pin to 1.6.1 lvm cookbook

**Comment by rshade** [comment]
@Stromweld thank you. I prefer pinning as it is a more structured version of dependency management. If you run into issues getting a pull request added in the future, feel free to mention me directly in the pull and I will look at it.

**Comment by Stromweld** [comment]
are you also working on getting the latest version of this cookbook added to the supermarket?

**Comment by Stromweld** [comment]
Thanks for the merge too.

**Comment by cdwilhelm** [comment]
@Stromweld sorry for the delay.  ownership of the cookbook has occured and we are working thorough the new release process.  Anyway, the new cookbook has been uploaded to the supermarket.

Cheers!

**Comment by Stromweld** [comment]
cool thanks

**Pull request merged**
